# Generated by Django 6.0.4 on 2026-04-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_alter_tarefas_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefas',
            name='prioridade',
            field=models.CharField(choices=[('URGENTE', 'Urgente'), ('NAO_URGENTE', 'Não urgente')], default='NAO_URGENTE', max_length=20),
        ),
    ]
